[package]
name = "congkak-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "congkak_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
